const reference = [
  {
    author: "Lauri Nummenmaaa 외 3인",
    title: "Bodily maps of emotions",
    year: "2013",
    sourceTitle: "필란드 알토대학교 미국국립과학원회보 학술지",
    link: "https://www.pnas.org/doi/pdf/10.1073/pnas.1321664111",
  },
  {
    author: "급여정보분석실 급여정보운영부",
    title: "최근 5년(2017~2021년) 우울증과 불안장애 진료현황 분석",
    year: "2022",
    sourceTitle: "건강보험심사평가원",
    link: "https://www.hira.or.kr/bbsDummy.do?pgmid=HIRAA020041000100&brdScnBltNo=4&brdBltNo=10627",
  },
  {
    author: "김미경",
    title: "2021년 정신건강실태조사 결과 발표",
    year: "2021",
    sourceTitle: "보건복지부",
    link: "https://www.mohw.go.kr/react/al/sal0301vw.jsp?PAR_MENU_ID=04&MENU_ID=0403&CONT_SEQ=369088",
  },
  {
    author: "김성윤 외 4인",
    title: "질환백과-불안 장애(Anxiety disorder)",
    year: "2023",
    sourceTitle: "서울아산병원",
    link: "https://www.amc.seoul.kr/asan/healthinfo/disease/diseaseDetail.do?contentId=31582&tabIndex=0",
  },
  {
    author: "김총기",
    title: "감정을 잘 조절하는 방법은?",
    year: "2022",
    sourceTitle: "정신의학신문",
    link: "http://www.psychiatricnews.net/news/articleView.html?idxno=33427",
  },
  {
    author: "미국정신분석학회",
    title: "정신분석용어사전-수치심",
    year: "2002",
    sourceTitle: "네이버 지식백과",
    link: "https://terms.naver.com/entry.naver?docId=655869&cid=48639&categoryId=48639",
  },
  {
    author: "박형주",
    title: "[일상 속 뇌과학] 나쁜 기억은 왜 쉽게 잊혀지지 않을까",
    year: "2023",
    sourceTitle: "동아사이언스",
    link: "https://www.dongascience.com/news.php?idx=59089",
  },
  {
    author: "손매남",
    title: "[뇌치유상담] 분노의 뇌, 전두엽의 기능이 저하된다",
    year: "2022",
    sourceTitle: "기독일보",
    link: "https://www.christiandaily.co.kr/news/117317#",
  },
  {
    author: "온라인 중앙일보",
    title:
      "사회공포증 증상, 사람 앞에서 극도의 긴장감·두려움·부끄러움 느낀다면",
    year: "2016",
    sourceTitle: "The JoongAng",
    link: "https://www.joongang.co.kr/article/19648931#home",
  },
  {
    author: "이지영",
    title: "2. 우리가 감정을 느끼는 이유-감정은 정보이다",
    year: "2021",
    sourceTitle: "프리미엄콘텐츠",
    link: "https://contents.premium.naver.com/subblack/knowledge/contents/211115171356228Ne",
  },
  {
    author: "최현석",
    title: "인간의 모든 감정-슬픔신경계",
    year: "2011",
    sourceTitle: "네이버 지식백과",
    link: "https://terms.naver.com/entry.naver?docId=1719780&cid=42063&categoryId=42063",
  },
  {
    author: "현",
    title: "감정표현단어모음집",
    year: "2016",
    sourceTitle: "더나은복지세상",
    link: "https://www.welfare24.net/ab-3864-24",
  },
  {
    author: "홍문기",
    title: "[홍문기의 아동친화도시 이야기]행복한 사람들의 특징“감정 표현”",
    year: "2023",
    sourceTitle: "새전북신문",
    link: "http://sjbnews.com/news/news.php?number=775000",
  },
];
